### ISSUE TITLE
Unable to set correct AWS LB Protocoll

### ISSUE THREAD

**Issue by amd87hh** [odavid/k8s-helm-charts#25]
Hi,

I'm trying to set up an AWS Loadbalancer, but the protocolls for jnlp and ssh are set to HTTP instead of TCP. And I don't know how to change them.

```
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:xxx
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  httpPort: 443
```

![Screenshot 2021-08-03 at 14-36-33 EC2 Management Console](https://user-images.githubusercontent.com/41955712/128034757-238a722e-2140-4e0c-a310-054a48828e97.png)

Thanks for help!

**Comment by odavid** [comment]
this is how I configured mine...

```yaml
service:
  type: LoadBalancer
  httpPort: 443
  externalTrafficPolicy: Local
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "60"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:<YOUR Certiticate ARN>"
```

![image](https://user-images.githubusercontent.com/861953/128072448-15cd0077-8df3-48a9-8318-0f6e23f06383.png)
